#!/usr/bin/python3
# This code write by (Mr.nope)
#   ❚█══Hack Tools══█❚
# Hacking 2.3.0
import os
import time
import random
import requests
import platform
import sys
class color:
    green = '\033[92m'
    red = '\033[91m'
    End = '\033[0m'
    blue = '\033[96m'
    line = '\033[4m'
    darkblue = '\033[34m'
HackTools = "\nHackTools ~>>> "
Error = "Error HackTools!"
ex = color.green + "Exiting package!" + color.End
system = platform.uname()[0]
def title():
    os.system("printf '\033]2;Hacking\a'")
def cls():
    if system == 'Linux':
        os.system("clear")
    elif system == 'Windows':
        os.system("cls")
continue_Hacktool = "Do you want to continue? [y/n] "
color_r=[color.green + """
██████████
██■████■██
██████████
██████████
█ █ █ █ █    (Hack Tools!)
██████████
""" + color.End, color.green +
"""
┈┈┈╲┈┈┈┈╱
┈┈┈╱VIRUZ▔▔╲
┈┈┃┈▇┈┈▇┈┃
╭╮┣━━━━━━┫╭╮
┃┃┃┈┈┈┈┈┈┃┃┃
╰╯┃┈┈┈┈┈┈┃╰╯
┈┈╰┓┏━━┓┏╯
┈┈┈╰╯┈┈╰╯""" + color.End, color.blue + """
    .
    ║\.
    ║▒\.
    ║▒▒\
    ║░▒ ║
    ║░▒║    (HackTools)
    ║░▒ ║   (Mr.nope)
    ║░▒║    (version):(1.3.0)
    ║░▒║
    ║░▒ ║ """ + color.red + "----[ https://github.com/mrprogrammer2938/ ]----- " + color.blue + """
    ║░▒║
    ║░▒ ║
    ║░▒║
▓▓▓▓▓▓▓
     ]█▓[
     ]█▓[
     ]█▓[\n""" + color.End,color.red + """
    __________
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
   ║▒▒▒▒▒▒▒▒▒▒║
  ╔════════════╗
  ║██████████╚╗
  ║██╔══╗█╔═╗█║
  ║██║╬╔╝█╚╗║█║ """ + color.green + "Hacking tools!" + color.red + """
  ║██╚═╝█║█╚╝█║
  ╚╗█████████═╝
     ╚╗║╠╩╩╩╩╩╝
      ║║┈┈┈█▐█████▒.｡oO """ + color.green + "usage: hacking" + color.red + """
      ║██╠╦╦╦╗
      ╚╗██████
       ╚════╝\n""" + color.End,color.green + '''


88  88    db     dP""b8 88  dP     888888  dP"Yb   dP"Yb  88     .dP"Y8
88  88   dPYb   dP   `" 88odP        88   dP   Yb dP   Yb 88     `Ybo."
888888  dP__Yb  Yb      88"Yb        88   Yb   dP Yb   dP 88  .o o.`Y8b
88  88 dP""""Yb  YboodP 88  Yb       88    YbodP   YbodP  88ood8 8bodP'
''' + color.End, color.darkblue + '''
        m    m               #            mmmmmmm               ""#
        #    #  mmm    mmm   #   m           #     mmm    mmm     #     mmm
        #mmmm# "   #  #"  "  # m"            #    #" "#  #" "#    #    #   "
        #    # m"""#  #      #"#             #    #   #  #   #    #     """m
        #    # "mm"#  "#mm"  #  "m           #    "#m#"  "#m#"    "mm  "mmm" \n''' + color.End, color.blue + """
     ╔╦╦╦╦╦╦╦╦╦╦╗
     ╠╬╬╬╬╬╬╬╬╬╬╣
     ╠╬╬█╬╬╬╬█╬╬╣
     ╠╬╬╬╬╬╬╬╬╬╬╣ (Hack Tools !)
     ╠╬████████╬╣
     ╠╬█╬╬╬╬╬╬█╬╣
     ╚╩╩╩╩╩╩╩╩╩╩╝ """ + color.End, color.End + """
      ▄ .▄ ▄▄▄·  ▄▄· ▄ •▄   ▄▄▄▄▄            ▄▄▌  .▄▄ ·
      ██▪▐█▐█ ▀█ ▐█ ▌▪█▌▄▌▪  •██   ▄█▀▄  ▄█▀▄ ██•  ▐█ ▀.
      ██▀▐█▄█▀▀█ ██ ▄▄▐▀▀▄·   ▐█.▪▐█▌.▐▌▐█▌.▐▌██▪  ▄▀▀▀█▄
      ██▌▐▀▐█ ▪▐▌▐███▌▐█.█▌   ▐█▌·▐█▌.▐▌▐█▌.▐▌▐█▌▐▌▐█▄▪▐█
      ▀▀▀ · ▀  ▀ ·▀▀▀ ·▀  ▀   ▀▀▀  ▀█▄▀▪ ▀█▄▀▪.▀▀▀  ▀▀▀▀ """, color.green + """
      █████████
      █▄█████▄█
      █▼▼▼▼▼
      █        (Hi!)
      █▲▲▲▲▲
      █████████
      ██ ██""" + color.End, color.blue + """
      ┈┈┈┈┈┈▕▔╲
      ┈┈┈┈┈┈┈▏▕
      ┈┈┈┈┈┈┈▏▕▂▂▂
      ▂▂▂▂▂▂╱┈▕▂▂▂▏
      ▉▉▉▉▉┈┈┈▕▂▂▂▏""" + color.red + "usage: hacking :)" + color.blue + """
      ▉▉▉▉▉┈┈┈▕▂▂▂▏
      ▔▔▔▔▔▔╲▂▕▂▂▂▏""" + color.End]
def cls():
    os.system("clear")
random.shuffle(color_r)
HackToolslogo = color_r[0]
def hacking():
    title()
    cls()
    print(HackToolslogo + "\n")
    print(color.red + """
______________________________________________""" + color.blue + """
  ----[ This code write by (Mr.nope)  ]----
  [version 1.0.0]""" + color.red + """
  [[  Mr.nope github account : https://github.com/mrprogrammer2938/ ]]---""" + color.darkblue + """
   *   usage:    hackingtool          ---[for start ]--  *""" + color.line + """
                         (Hack tools)""" + color.red + """
                   ______________________________________________ \n""" + color.End)
    print("\n{1}.Web Hacking")
    print("{2}.Password Attack")
    print("{3}.Explotion tools")
    print("{4}.Wirless testing")
    print("{5}.soial Engineer")
    print("{6}.cam Hackers")
    print("{7}.web informtion")
    print("{8}.About Us")
    print("{9}.Help")
    print("{10}.update and uninstall")
    print("{99}.Exit or Ctrl + D")
    choose = input(HackTools)
    if choose == '1':
      webhacking()
    elif choose == '2':
        passwordattack()
    elif choose == '3':
        explotion()
    elif choose == '4':
        wirlessattack()
    elif choose == '5':
        soialEngineer()
    elif choose == '6':
        camhackers()
    elif choose == '7':
        webinfo()
    elif choose == '8':
        about()
    elif choose == '9':
        help()
    elif choose == '10':
        upun()
    elif choose == '99':
        ext()
    elif choose == 'exit':
        ext()
    elif choose == 'quit':
        ext()
    elif choose == '' or choose == ' ':
        hacking()
    else:
        cls()
        print(choose + color.red + " Not found!" + color.End)
        try_menu = input("\npress Enter....")
        if try_menu == '':
            hacking()
        else:
            hacking()
def webhacking():
    cls()
    print(color.blue)
    os.system("figlet web Hacking")
    print(color.End)
    print("{1}.brutex")
    print("{2}.serverscan")
    print("{3}.hack web")
    print("{99}.mein menu")
    choose2 = input(HackTools)
    if choose2 == '1':
        cls()
        os.system("figlet brutex")
        os.system("git clone https://github.com/1N3/brutex")
        time.sleep(1)
        print(color.green + "brutex installed!" + color.End)
        time.sleep(0.50)
        try1()
    elif choose2 == '2':
        cls()
        os.system("figlet serverscan")
        os.system("git clone https://github.com/mrprogrammer2938/serverscan")
        time.sleep(1)
        print(color.green + "serverscan installed!" + color.End)
        time.sleep(0.50)
        try1()
    elif choose2 == '3':
        cls()
        os.system("figlet brutex")
        os.system("git clone https://github.com/topics/web-hacking/ hackweb/")
        time.sleep(1)
        print(color.green + "hack web installed!" + color.End)
        time.sleep(0.50)
        try1()
    elif choose2 == '4':
        cls()
        os.system("git clone https://github.com/mrprogrammer2938/Brute-Force")
        try1()
    elif choose2 == '99':
         hacking()
    else:
        webhacking()
def passwordattack():
    cls()
    print(color.blue)
    os.system("figlet password Attack")
    print(color.End)
    print("{1}.cupp")
    print("{2}.password-Attack")
    print("{3}.password cracker")
    print("{4}.mein menu")
    choose3 = input(HackTools)
    if choose3 == '1':
      cls()
      os.system("figlet cupp")
      os.system("git clone https://github.com/Mebus/cupp")
      time.sleep(1)
      print(color.green + "cupp installed!" + color.End)
      time.sleep(2)
      try2()
    elif choose3 == '2':
        cls()
        os.system("figlet password attack")
        os.system("git clone https://github.com/topics/password-attacks/ passwordattack/")
        time.sleep(1)
        print(color.green + "password attack installed!" + color.End)
        time.sleep(2)
        try2()
    elif choose3 == '3':
        cls()
        os.system("figlet password cracker")
        os.system("git clone https://github.com/mthambipillai/password-cracker/ passwordcracker/")
        time.sleep(1)
        print(color.green + "password cracker installed!" + color.white)
        time.sleep(2)
        try2()
    elif choose3 == '99':
        hacking()
    else:
        passwordattack()
def explotion():
    time.sleep(1)
    cls()
    print(color.blue)
    os.system("figlet Explotion")
    print(color.End)
    print("{1}.metsaploit")
    print("{2}.explotion feiled")
    print("{3}.isf")
    print("{99}.main menu")
    choose4 = input(Hack_Tool)
    if choose4 == '1':
        cls()
        os.system("figlet metsaploit")
        os.system("git clone https://github.com/rapid7/metasploit-framework/ metsaploit/")
        time.sleep(1)
        print(color.green + "metsaploit installed!" + color.End)
        time.sleep(2)
        try3()
    elif choose4 == '2':
        cls()
        os.system("figlet explotion feiled")
        os.system("git cone https://github.com/tyrantgit/ExplosionField/ exploitsionfield")
        time.sleep(1)
        print(color.green + "exploitionfield installed" + color.End)
        time.sleep(2)
        try3()
    elif choose4 == '3':
        os.system("clear")
        os.system("figlet isf")
        os.system("git clone https://github.com/w3h/isf")
        time.sleep(1)
        print(color.green + "isf installed!" + color.End)
        time.sleep(2)
        try3()
    elif choose4 == '99':
        hacking()
    else:
        explotion()
def wirlessattack():
    cls()
    print(color.line)
    os.system("figlet wirless Attack")
    print(color.End)
    print("{1}.wirless Attack")
    print("{2}.wifi attack")
    print("{3}.wifi arsenal")
    print("{99}.mein menu")
    choose5 = input(HackTools)
    if choose5 == '1':
        cls()
        os.system("figlet wirless Attack")
        os.system("git clone https://github.com/topics/wireless-attacks/ wirlessattack/")
        time.sleep(1)
        print(color.green + "wirless attack installed!" + color.End)
        time.sleep(2)
        try4()
    elif choose5 == '2':
        os.system("clear")
        os.system("figlet wifi attack")
        os.system("git clone https://github.com/AaronVigal/WiFi-Attack/ wifiattack/")
        time.sleep(1)
        print(color.green + "wifi attack installed" + color.End)
        time.sleep(2)
        try4()
    elif choose5 == '3':
        cls()
        os.system("figlet wifi arsenal")
        os.system("git clone https://github.com/0x90/wifi-arsenal/ wifiarsenal/")
        time.sleep(1)
        print(color.green + "wifi arsenal installed" + color.End)
        time.sleep(2)
        try4()
    elif choose5 == '99':
        hacking()
    else:
        wirlessattack()
def soialEngineer():
    cls()
    print(color.green)
    os.system("figlet soial Engineer")
    print("{1}.soial Engineer stoolkit")
    print("{99}.mein menu")
    choose6 = str(input(HackTools))
    if choose6 == '1':
      cls()
      os.system("figlet setoolkit")
      os.system("git clone https://github.com/trustedsec/social-engineer-toolkit/ setoolkit")
      time.sleep(1)
      print(color.green + "setoolkit installed!" + color.End)
      time.sleep(2)
      try5()
    elif choose6 == '99':
        hacking()
    else:
        soialEngineer()
def camhackers():
    time.sleep(1)
    os.system("clear")
    os.system("figlet cam Hackers")
    print("{1}.cam Hackers")
    print("{2}.cam hackers(2)")
    print("{3}.main menu")
    choose7 = input(HackTools)
    if choose7 == '1':
      time.sleep(1)
      cls()
      os.system("figlet cam Hackers")
      os.system("git clone https://github.com/mrprogrammer2938/cam-Hackers")
      time.sleep(2)
      try6()
    elif choose7 == '2':
        cls()
        os.system("figlet cam Hackers")
        os.system("git clone https://github.com/AngelSecurityTeam/Cam-Hackers")
        time.sleep(2)
        try6()
    elif choose7 == '99':
        hacking()
    else:
        camhackers()
def webinfo():
    cls()
    print(color.blue)
    os.system("figlet web informtion")
    print(color.End)
    print("{1}.web-information-gathering")
    print("{2}.serverscan")
    print("{99}.mein menu")
    choose8 = input(HackTools)
    if choose8 == '1':
      cls()
      os.system("figlet web informtion")
      os.system("git clone https://github.com/zahidin/web-information-gathering/ webinfomtion/")
      time.sleep(2)
      try7()
    elif choose8 == '2':
        cls()
        os.system("figlet serverscan")
        os.system("git clone https://github.com/mrprogrammer2938/serverscan")
        time.sleep(2)
        try7()
    elif choose8 == '99':
        hacking()
    else:
        webinfo()
def about():
    os.system("clear")
    time.sleep(1)
    print(color.line)
    os.system("figlet HackTools")
    print("\n")
    time.sleep(0.5)
    print("This code write by Ms.nope\n")
    time.sleep(0.5)
    print("ms.nope github account : https://github.com/mrprogrammer2938/\n")
    time.sleep(1)
    print("version 1.2.0\n")
    time.sleep(2)
    try_menu = input("\npress Enter...")
    if try_menu == '':
        hacking()
    else:
        hacking()
def try7():
    try_to_menu6 = input("\npress Enter...")
    if try_to_menu6 == '':
        webinfo()
    else:
        webinfo()
def help():
    time.sleep(1)
    os.system("clear")
    print("""
This code write by (Mr.nope)
usage:
     {1} - install web hacking tools
     {2} - password attacking tools
     {3} - explotion tools
     {4} - wirless attacking tools
     {5} - soial Enginner tools
     {6} - cam hackers
     {7} - web informtion
     {8} - About us
     {9} - Help
     {10} - Exit """)
    time.sleep(2)
    try_menu = input("\npress Enter...")
    if try_menu == '':
        hacking()
    else:
        hacking()
def ext():
    cls()
    print(color.green + "Exiting..." + color.End)
    sys.exit()
def upun():
    time.sleep(1)
    os.system("clear")
    print(color.blue)
    os.system("toilet Hackingtool")
    print(color.End)
    print("\n{1}.update")
    print("{2}.uninstall")
    print("{99}.mein menu")
    choose10 = str(input(HackTools))
    if choose10 == '1':
      cls()
      time.sleep(1)
      os.system("cd .. && sudo rm -r hackingtools && git clone https://github.com/mrprogrammer2938/hackingtools && cd .. && cd hackingtools && ls")
      time.sleep(1)
      print(color.green + "finish!" + color.End)
      print("""
usage:
      bash install.sh""")
      sys.exit()
    elif choose10 == '2':
        cls()
        print(color.green + "unistalling..." + color.End)
        time.sleep(2)
        os.system("cd .. && sudo rm -r hackingtools && cd .. && cd /usr/local/bin && sudo rm -r hacking")
        time.sleep(1)
        print("hackingtools package uninstalled!")
        time.sleep(1)
        print(color.green + "good bye!" + color.End)
        sys.exit()
    elif choose10 == '99':
        hacking()
    else:
        upun()
def try1():
    try_to_menu1 =input("\npress Enter...")
    if try_to_menu1 == '':
        webhacking()
    else:
        webhacking()
def try2():
    try_to_menu2 = input("\npress Enter...")
    if try_to_menu2 == '':
        pass
    else:
        pass
def try3():
    try_to_menu3 = input("\npress Enter...")
    if try_to_menu3 == '':
        pass
    else:
        pass
def try4():
    try_to_menu4 = input("\npress Enter...")
    if try_to_menu4 == '':
        wirlessattack()
    else:
        wirlessattack()
def try5():
    try_to_menu4 = input("\npress Enter...")
    if try_to_menu4 == '':
        soialEngineer()
    else:
        soialEngineer()
def try6():
    try_to_menu5 = input("\npress Enter...")
    if try_to_menu5 == '':
        camhackers()
    else:
        camhackers()
if __name__ == '__main__':
    try:
        try:
            hacking()
        except EOFError:
            print("\nCtrl + D")
            print("\nExiting...")
            sys.exit()
    except KeyboardInterrupt:
        print("\nCtrl + C")
        print("\nHacking Tool Stop!")
        try_to_main_menu = input("\npress Enter...")
        if try_to_main_menu == '':
            hacking()
        else:
            hacking()
